### ISSUE TITLE
 My servlet Only Returns red

### ISSUE THREAD

**Issue by alexsrs** [pla1/Misc#2]
My servlet Only Returns red , I can not identify the problem , help me?

**Comment by pla1** [comment]
I use this on Ubuntu Linux server. Check your output from this command: `ping -c 1 -W 1 8.8.8.8` against the constants in [this if statement](https://github.com/pla1/Misc/blob/master/src/com/pla/misc/PingImageServlet.java#L66).  Sorry about the late reply. Thanks, PLA
